### PR TITLE
fix: rely on get_golem_wd where useful

### LINKED ISSUE #844: All functions that read file should rely on golem::get_golem_wd
For example, 

```
get_current_config <- function(
  path = ".",
```

should be pkg = get_golem_wd()

### PR DESCRIPTION
**Pull request by ilyaZar**
This PR should fix #844 

- files that receive a change are referenced in the commits in turn
- files not changed (still have an ".") are the bootstrap_type funcs.:
    -  `attachment_create_renv_for_prod`
    - `pkgload_load_all`
    - `roxygen2_roxygenise`
    - `usethis_proj_set`
    - `enable_roxygenize`

Not sure about those, they are all unexported and called internally, probably with correct argument passing from the top level functions that should now have all the `get_golem_wd()`.

### CODE REVIEW

File: R/add_dockerfiles_renv.R [hunk 1]
```diff
@@ -110,7 +110,7 @@ add_dockerfile_with_renv_ <- function(
       )
     ) {
       out <- pkgbuild::build(
-        path = ".",
+        path = get_golem_wd(),
```
Comment (ColinFay) [inline R/add_dockerfiles_renv.R:113]: I think here we should rely on passing arg from the parent function, so that if source_folder is changed, it's passed to pkgbuild::build().

Comment (ilyaZar) [reply R/add_dockerfiles_renv.R]: done. 

let me know about any changes in the bootstrap_type functions (see PR's initial comment)   @ColinFay  

these functions are used internally only, taking arguments from their respective parent functions. still might be useful to have `get_golem_wd` defaults instead of "."

File: R/config.R [hunk 2]
```diff
@@ -9,7 +9,7 @@
 
 #' @importFrom attempt attempt is_try_error
 guess_where_config <- function(
-  path = golem::pkg_path(),
+  path = get_golem_wd(),
```
Comment (ColinFay) [inline R/config.R:12]: Given that these ones try to guess where the config.yaml is and that get_golem_wd() calls `get_golem_things()` which calls `get_current_config()` which calls `guess_where_config()`, we'll need to keep them as before if we want to avoid an infinite call stack :) 

```suggestion
  path = golem::pkg_path(),
```

File: R/config.R [hunk 3]
```diff
@@ -60,8 +60,8 @@ guess_where_config <- function(
 #' @param path Path to start looking for the config
 #'
 #' @export
-get_current_config <- function(path = getwd()) {
-  # We check wether we can guess where the config file is
+get_current_config <- function(path = get_golem_wd()) {
```
Comment (ColinFay) [inline R/config.R:63]:
```suggestion
get_current_config <- function(path = getwd()) {
```

**Review by ColinFay — APPROVED** [review]
